(defproject gorilla-test "0.1.0-SNAPSHOT"
  :description "A test project for the Gorilla REPL."
  :dependencies [[org.clojure/clojure "1.7.0"]
                 [com.vijaykiran/docjure "1.7.0"]
                 [org.clojure/core.match "0.2.2"]
                 [org.clojure/core.unify "0.5.6"]
                 [clojurewerkz/neocons "3.1.0"]
                 [clj-gremlin "0.0.3"]
                 [clj-blueprints2 "0.0.1" :exclusions [com.tinkerpop.blueprints/blueprints-core]]
                 [gavagai "0.3.2"]
                 [prismatic/plumbing "0.5.2"]
                 [clojureql "1.0.4"]
                 [lein-kibit "0.1.2"]
                 [rplevy-draker/wabbitmq "0.3.0" :exclusions [org.clojure/clojure]]
                 [com.mysql/connectorj "5.1.12"]
                 [hiccup "1.0.5"]
                 [expresso "0.2.0"]
                 [aysylu/loom "0.5.4"]
                 [loom-gorilla "0.1.0"]
                 [org.clojure/data.xml "0.0.8"]
                 [incanter-gorilla "0.1.0"]
                 [gorilla-renderable "2.0.0"]
                 [com.microsoft/sqljdbc4 "3.0"]
                 [cn.guoyukun.jdbc/db2jcc "1.4.2"]
                 [cn.guoyukun.jdbc/db2jcc_license_cu "1.4.2"]
                 [com.taoensso/carmine "2.12.2" :exclusions [org.clojure/clojure]]
                 [com.ashafa/clutch "0.4.0"]
                 [com.uswitch/clj-soap "0.2.3"]
                 [proto-repl "0.1.2"]
                 [abrade "0.1.8"]]
  :main ^:skip-aot gorilla-test.core
  :target-path "target/%s"
  :plugins [[lein-gorilla "0.3.6"]
            [lein-localrepo "0.5.3"]]
  :profiles {:uberjar {:aot :all}})
